### Get root directory
GET http://localhost:5173

### register a user (POST /auth/register)
POST http://localhost:5173/auth/register
Content-Type: application/json

// data to send
{
    "email": "test@gmail.com",
    "password": "123123",
    "name": "John Doe"
}

### register a user (POST /auth/register)
POST http://localhost:5173/auth/register
Content-Type: application/json

// data to send
{
    "email": "test2@gmail.com",
    "password": "123123",
    "name": "John Doe"
}

### login a user (POST /auth/login)
POST http://localHost:5173/auth/login
Content-Type: application/json

{
    "email": "test2@gmail.com",
    "password": "123123"
}

### connect a plaid sandbox account
POST http://localhost:5173/plaid/create_link_token
Content-Type: application/json

{
    "userId": "123456"
}

### 
POST http://localhost:5173/plaid/exchange_public_token
Content-Type: application/json

{
    "userId": "123456",
    "public_token": "123456789"
}