// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrations use DIRECT_URL (session pooler / direct) — not the transaction pooler
  datasource: {
    url: env("DIRECT_URL"),
  },
});
